language: node_js
node_js: stable
notifications:
  email: false
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache:
  directories:
  - $HOME/.yarn-cache
install:
  - yarn
script:
  - npm run build
